#默认使用配置
spring:
  profiles:
      active: dev
  http:
    multipart:
      enabled: true
      max-file-size: 2MB
server:
  port: 8080

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.aima.testsys.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true


commonDS:
  # 配置初始化大小、最小、最大
  initialSize: 2
  minIdle: 2
  maxActive: 5
  #配置获取连接等待超时的时间
  maxWait: 60000
  #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  timeBetweenEvictionRunsMillis: 60000
  #配置一个连接在池中最小生存的时间，单位是毫秒
  minEvictableIdleTimeMillis: 60000

  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  #打开PSCache，并且指定每个连接上PSCache的大小
  poolPreparedStatements: true
  maxPoolPreparedStatementPerConnectionSize: 5
  #配置监控统计拦截的filters，去掉后监控界面sql无法统计
  filters: stat,wall,slf4j
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  useGlobalDataSourceStat: true
  #durid监控配置
  loginUsername: star
  loginPassword: Star1234
  resetEnable: false
  rootPath: /druid/*

  #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid2/*
---

#开发配置
spring:
  profiles: dev

#  datasource:
#    url: jdbc:mysql://192.168.3.58:3306/lgd_db?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#    username: edu
#    password: 1q2w#e$r
#    driver-class-name: com.mysql.jdbc.Driver

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testsystem?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: abc123
    driver-class-name: com.mysql.jdbc.Driver

  session:
    store-type: none
  #配置日志
logging:
  config: classpath:logback-spring.xml

